services:
  postgres:
    image: postgres:15
    container_name: cash-control-postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: cash_control
    ports:
      - "5432:5432"
